### ISSUE TITLE
non-issue: Wow! We've Made this Site Awesome!!

### ISSUE THREAD

**Issue by e-coders** [Educational-Websites/educational-websites.github.io#2]
non-issue: Wow! We've Made this Site Awesome!!
This isn't an issue but there have no discussion tab So I came here.
Wow! How many We all have together made this an Awesome Responsive site!!
I've Added Contributors in one page, Tutorials and Projects in Different Sections and more changes!!

**Comment by Genius398** [comment]
Thanks!

**Comment by e-coders** [comment]
That's great!! I'm talking About this to u on gmail...Come on gmail.

**Comment by Genius398** [comment]
> That's great!! I'm talking About this to u on gmail...Come on gmail.

Sorry I'm going to bed

**Comment by Genius398** [comment]
> That's great!! I'm talking About this to u on gmail...Come on gmail.

Around 8 am I'm on
